import * as TJS from "typescript-json-schema";
import * as path from "path";
import * as fs from "fs";

const program = TJS.getProgramFromFiles([path.join(__dirname, "src", "interface", "fcm-requests.ts")], null, null);

const generator = TJS.buildGenerator(program, {
  required: true
});
let FCMMessage = generator.getSchemaForSymbol("FCMMessage");
let FCMTokenMessage = generator.getSchemaForSymbol("FCMTokenMessage");

fs.writeFileSync(
  path.join(__dirname, "validators", "validators.ts"),
  `// This file is automatically generated by "npm run build-interface-validation". Do not edit it directly.
  
  export default ` + JSON.stringify({ FCMMessage, FCMTokenMessage }, null, 2)
);
