import * as TJS from "typescript-json-schema";
import * as path from "path";
import * as fs from "fs";

const program = TJS.getProgramFromFiles(
  [
    path.join(__dirname, "src", "interface", "fcm-requests.ts"),
    path.join(__dirname, "src", "interface", "env.ts"),
    path.join(__dirname, "src", "interface", "subscription-types.ts")
  ],
  null,
  null
);

const generator = TJS.buildGenerator(program, {
  required: true,
  noExtraProps: true
});

let interfaces = [
  "FCMMessage",
  "FCMTokenMessage",
  "FCMTopicMessage",
  "EnvironmentVariables",
  "iOSSubscription",
  "WebSubscription"
];

let result = generator.getSchemaForSymbols(interfaces);

fs.writeFileSync(
  path.join(__dirname, "src", "validators", "validators.ts"),
  `// This file is automatically generated by "npm run build-interface-validation". Do not edit it directly.
  
  export default ` + JSON.stringify(result, null, 2)
);
