version: '3'
services:
  pushkin:
    image: "mhart/alpine-node:8"
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    # command: "npm run dev"
    working_dir: "/code"
    links:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/postgres
  postgres:
    image: "onjin/alpine-postgres"
    volumes:
      - ./.dev-pgdata:/db-data
    environment:
      PGDATA: /db-data