"use strict";
// This file is automatically generated by "npm run build-interface-validation". Do not edit it directly.
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    "$schema": "http://json-schema.org/draft-06/schema#",
    "definitions": {
        "FCMMessage": {
            "type": "object",
            "properties": {
                "data": {},
                "notification": {
                    "$ref": "#/definitions/FCMNotification"
                },
                "android": {
                    "$ref": "#/definitions/FCMAndroidConfig"
                },
                "webpush": {
                    "$ref": "#/definitions/FCMWebpushConfig"
                },
                "apns": {
                    "$ref": "#/definitions/FCMApnsConfig"
                }
            },
            "required": [
                "notification"
            ]
        },
        "FCMTokenMessage": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "data": {},
                "notification": {
                    "$ref": "#/definitions/FCMNotification"
                },
                "android": {
                    "$ref": "#/definitions/FCMAndroidConfig"
                },
                "webpush": {
                    "$ref": "#/definitions/FCMWebpushConfig"
                },
                "apns": {
                    "$ref": "#/definitions/FCMApnsConfig"
                }
            },
            "required": [
                "notification",
                "token"
            ]
        },
        "FCMTopicMessage": {
            "type": "object",
            "properties": {
                "topic": {
                    "type": "string"
                },
                "data": {},
                "notification": {
                    "$ref": "#/definitions/FCMNotification"
                },
                "android": {
                    "$ref": "#/definitions/FCMAndroidConfig"
                },
                "webpush": {
                    "$ref": "#/definitions/FCMWebpushConfig"
                },
                "apns": {
                    "$ref": "#/definitions/FCMApnsConfig"
                }
            },
            "required": [
                "notification",
                "topic"
            ]
        },
        "EnvironmentVariables": {
            "type": "object",
            "properties": {
                "FIREBASE_AUTH_KEY": {
                    "type": "string"
                },
                "DATABASE_URL": {
                    "type": "string"
                },
                "USER_API_KEY": {
                    "type": "string"
                },
                "ADMIN_API_KEY": {
                    "type": "string"
                },
                "NODE_ENV": {
                    "type": "string"
                },
                "FIREBASE_PRIVATE_KEY": {
                    "type": "string"
                },
                "FIREBASE_CLIENT_EMAIL": {
                    "type": "string"
                },
                "FCM_PROJECT": {
                    "type": "string"
                },
                "ALLOWED_ORIGINS": {
                    "type": "string"
                },
                "SERVER_PORT": {
                    "type": "string"
                },
                "TOPIC_PREFIX": {
                    "type": "string"
                },
                "VAPID_PUBLIC_KEY": {
                    "type": "string"
                }
            },
            "required": [
                "ADMIN_API_KEY",
                "DATABASE_URL",
                "FCM_PROJECT",
                "FIREBASE_AUTH_KEY",
                "FIREBASE_CLIENT_EMAIL",
                "FIREBASE_PRIVATE_KEY",
                "NODE_ENV",
                "TOPIC_PREFIX",
                "USER_API_KEY",
                "VAPID_PUBLIC_KEY"
            ]
        },
        "FCMNotification": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                }
            },
            "required": [
                "body",
                "title"
            ]
        },
        "FCMAndroidConfig": {
            "type": "object",
            "properties": {
                "collapse_key": {
                    "type": "string"
                },
                "priority": {
                    "enum": [
                        "high",
                        "normal"
                    ],
                    "type": "string"
                },
                "ttl": {
                    "type": "string"
                },
                "restricted_package_name": {
                    "type": "string"
                },
                "data": {},
                "notification": {
                    "$ref": "#/definitions/FCMAndroidNotification"
                }
            },
            "required": [
                "data",
                "notification",
                "priority"
            ]
        },
        "FCMAndroidNotification": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "sound": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "click_action": {
                    "type": "string"
                }
            },
            "required": [
                "click_action",
                "color",
                "icon",
                "sound",
                "tag"
            ]
        },
        "FCMWebpushConfig": {
            "type": "object",
            "properties": {
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "notification": {
                    "$ref": "#/definitions/FCMWebpushNotification"
                }
            }
        },
        "FCMWebpushNotification": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "badge": {
                    "type": "string"
                }
            }
        },
        "FCMApnsConfig": {
            "type": "object",
            "properties": {
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "payload": {
                    "$ref": "#/definitions/ApnsPayload"
                }
            },
            "required": [
                "headers",
                "payload"
            ]
        },
        "ApnsPayload": {
            "type": "object",
            "additionalProperties": {},
            "properties": {
                "apns": {
                    "$ref": "#/definitions/ApnsKeys"
                }
            },
            "required": [
                "apns"
            ]
        },
        "ApnsKeys": {
            "type": "object",
            "properties": {
                "alert": {
                    "$ref": "#/definitions/ApnsAlert"
                },
                "badge": {
                    "type": "number"
                },
                "sound": {
                    "type": "string"
                },
                "content-available": {
                    "type": "number",
                    "enum": [
                        1
                    ]
                },
                "category": {
                    "type": "string"
                },
                "thread-id": {
                    "type": "string"
                }
            }
        },
        "ApnsAlert": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "body": {
                    "type": "string"
                },
                "launch-image": {
                    "type": "string"
                }
            },
            "required": [
                "launch-image"
            ]
        }
    }
};
//# sourceMappingURL=validators.js.map