// This file is automatically generated by "npm run build-interface-validation". Do not edit it directly.
  
  export default {
  "FCMMessage": {
    "type": "object",
    "properties": {
      "data": {},
      "notification": {
        "$ref": "#/definitions/FCMNotification"
      },
      "android": {
        "$ref": "#/definitions/FCMAndroidConfig"
      },
      "webpush": {
        "$ref": "#/definitions/FCMWebpushConfig"
      },
      "apns": {
        "$ref": "#/definitions/FCMApnsConfig"
      }
    },
    "required": [
      "notification"
    ],
    "definitions": {
      "FCMNotification": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          }
        },
        "required": [
          "body",
          "title"
        ]
      },
      "FCMAndroidConfig": {
        "type": "object",
        "properties": {
          "collapse_key": {
            "type": "string"
          },
          "priority": {
            "enum": [
              "high",
              "normal"
            ],
            "type": "string"
          },
          "ttl": {
            "type": "string"
          },
          "restricted_package_name": {
            "type": "string"
          },
          "data": {},
          "notification": {
            "$ref": "#/definitions/FCMAndroidNotification"
          }
        },
        "required": [
          "data",
          "notification",
          "priority"
        ]
      },
      "FCMAndroidNotification": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          },
          "icon": {
            "type": "string"
          },
          "color": {
            "type": "string"
          },
          "sound": {
            "type": "string"
          },
          "tag": {
            "type": "string"
          },
          "click_action": {
            "type": "string"
          }
        },
        "required": [
          "click_action",
          "color",
          "icon",
          "sound",
          "tag"
        ]
      },
      "FCMWebpushConfig": {
        "type": "object",
        "properties": {
          "headers": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "data": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        },
        "required": [
          "data",
          "headers"
        ]
      },
      "FCMApnsConfig": {
        "type": "object",
        "properties": {
          "headers": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "payload": {
            "$ref": "#/definitions/ApnsPayload"
          }
        },
        "required": [
          "headers",
          "payload"
        ]
      },
      "ApnsPayload": {
        "type": "object",
        "additionalProperties": {},
        "properties": {
          "apns": {
            "$ref": "#/definitions/ApnsKeys"
          }
        },
        "required": [
          "apns"
        ]
      },
      "ApnsKeys": {
        "type": "object",
        "properties": {
          "alert": {
            "$ref": "#/definitions/ApnsAlert"
          },
          "badge": {
            "type": "number"
          },
          "sound": {
            "type": "string"
          },
          "content-available": {
            "type": "number",
            "enum": [
              1
            ]
          },
          "category": {
            "type": "string"
          },
          "thread-id": {
            "type": "string"
          }
        }
      },
      "ApnsAlert": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          },
          "launch-image": {
            "type": "string"
          }
        },
        "required": [
          "launch-image"
        ]
      }
    },
    "$schema": "http://json-schema.org/draft-06/schema#"
  },
  "FCMTokenMessage": {
    "type": "object",
    "properties": {
      "token": {
        "type": "string"
      },
      "data": {},
      "notification": {
        "$ref": "#/definitions/FCMNotification"
      },
      "android": {
        "$ref": "#/definitions/FCMAndroidConfig"
      },
      "webpush": {
        "$ref": "#/definitions/FCMWebpushConfig"
      },
      "apns": {
        "$ref": "#/definitions/FCMApnsConfig"
      }
    },
    "required": [
      "notification",
      "token"
    ],
    "definitions": {
      "FCMNotification": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          }
        },
        "required": [
          "body",
          "title"
        ]
      },
      "FCMAndroidConfig": {
        "type": "object",
        "properties": {
          "collapse_key": {
            "type": "string"
          },
          "priority": {
            "enum": [
              "high",
              "normal"
            ],
            "type": "string"
          },
          "ttl": {
            "type": "string"
          },
          "restricted_package_name": {
            "type": "string"
          },
          "data": {},
          "notification": {
            "$ref": "#/definitions/FCMAndroidNotification"
          }
        },
        "required": [
          "data",
          "notification",
          "priority"
        ]
      },
      "FCMAndroidNotification": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          },
          "icon": {
            "type": "string"
          },
          "color": {
            "type": "string"
          },
          "sound": {
            "type": "string"
          },
          "tag": {
            "type": "string"
          },
          "click_action": {
            "type": "string"
          }
        },
        "required": [
          "click_action",
          "color",
          "icon",
          "sound",
          "tag"
        ]
      },
      "FCMWebpushConfig": {
        "type": "object",
        "properties": {
          "headers": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "data": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        },
        "required": [
          "data",
          "headers"
        ]
      },
      "FCMApnsConfig": {
        "type": "object",
        "properties": {
          "headers": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "payload": {
            "$ref": "#/definitions/ApnsPayload"
          }
        },
        "required": [
          "headers",
          "payload"
        ]
      },
      "ApnsPayload": {
        "type": "object",
        "additionalProperties": {},
        "properties": {
          "apns": {
            "$ref": "#/definitions/ApnsKeys"
          }
        },
        "required": [
          "apns"
        ]
      },
      "ApnsKeys": {
        "type": "object",
        "properties": {
          "alert": {
            "$ref": "#/definitions/ApnsAlert"
          },
          "badge": {
            "type": "number"
          },
          "sound": {
            "type": "string"
          },
          "content-available": {
            "type": "number",
            "enum": [
              1
            ]
          },
          "category": {
            "type": "string"
          },
          "thread-id": {
            "type": "string"
          }
        }
      },
      "ApnsAlert": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "body": {
            "type": "string"
          },
          "launch-image": {
            "type": "string"
          }
        },
        "required": [
          "launch-image"
        ]
      }
    },
    "$schema": "http://json-schema.org/draft-06/schema#"
  }
}